branches:
- imageTag: 7799d4e
  name: cirrus-aug26-rel
- imageTag: ad05f49
  name: cirrus-dask-gw-v1
- imageTag: 67ddfca
  name: cirrus-faas
- imageTag: 68bf840
  name: cirrus-kmh
- imageTag: b956606
  name: cirrus-llm
- imageTag: 85a163b
  name: cirrus-mpi
- imageTag: 98e5e66
  name: main
