branches:
- imageTag: ad05f49
  name: cirrus-dask-gw-v1
- imageTag: c9882c4
  name: cirrus-deploy-addv1
- imageTag: 480c99e
  name: cirrus-faas
- imageTag: 68bf840
  name: cirrus-kmh
- imageTag: b956606
  name: cirrus-llm
- imageTag: 85a163b
  name: cirrus-mpi
- imageTag: 74f714d
  name: cirrus-varsha-traefik
- imageTag: 6ed1862
  name: main
