# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
# $ conda env create -f environment.yml && conda activate scraping && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

name: scraping
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - jupyterlab
  - python=3.10
  - requests-cache
  - pandas
  - pip
  - numpy
  - openpyxl
  - pip:
    - doc2docx
