# This is a basic workflow to help you get started with Actions

name: Sync Changes to docs in Main branch with arc-iframe branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Find docs commits
        id: docs_commits
        run: |
          echo "::set-output name=commits::$(git log origin/arc-iframe..main --format='%H' -- 'docs/')"

      - name: Checkout arc-iframe branch
        uses: actions/checkout@v2
        with:
          ref: 'arc-iframe'

      - name: Cherry-pick commits
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          for commit in ${{ steps.docs_commits.outputs.commits }}
          do
            git cherry-pick $commit || break
          done

      - name: Push changes
        run: |
          git push origin arc-iframe
